// <auto-generated />
namespace FromCodeFirst.Database.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class FirstDevChange4 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FirstDevChange4));
        
        string IMigrationMetadata.Id
        {
            get { return "201605172004049_FirstDevChange4"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
